In [1]:
from exact.layers import QDropout
import torch
import torch.nn

/home/akai/anaconda3/envs/EXACT/lib/python3.8/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [5]:
my_dropout = QDropout(0.5)

torch_dropout = torch.nn.Dropout(0.5)


input = torch.randn(3, 2, dtype=torch.float32, requires_grad=True, device='cuda')
grad_output = torch.randn(3, 2, dtype=torch.float32, device='cuda')
print(input)
print(grad_output)

tensor([[ 0.9682, -1.1541],
        [-1.2543, -2.3675],
        [ 0.3625,  0.5088]], device='cuda:0', requires_grad=True)
tensor([[-1.9086,  1.0621],
        [-0.3484, -0.8709],
        [-1.5969,  0.4912]], device='cuda:0')


In [6]:
my_output = my_dropout(input)
torch_output = torch_dropout(input)

In [10]:
print(my_dropout.training)
print(my_output)
print(torch_output)

True
tensor([[ 0.0000, -2.3083],
        [ 0.0000,  0.0000],
        [ 0.0000,  1.0176]], device='cuda:0',
       grad_fn=<CppNode<ActQuantizedDropout>>)
tensor([[ 0.0000, -2.3083],
        [-2.5087,  0.0000],
        [ 0.7249,  0.0000]], device='cuda:0', grad_fn=<FusedDropoutBackward>)


In [7]:
print(torch.allclose(my_output, torch_output))

False


In [11]:
# my_dropout.backward(grad_output)
torch_output.backward(grad_output)

AttributeError: 'QDropout' object has no attribute 'backward'

In [12]:
# print(torch.allclose(input.grad, torch_output.grad))
print(grad_output)
print(torch_output.grad)

tensor([[-1.9086,  1.0621],
        [-0.3484, -0.8709],
        [-1.5969,  0.4912]], device='cuda:0')
None


/tmp/ipykernel_43471/297168353.py:3: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more information.
  print(torch_output.grad)
